# Generated by Django 5.0.3 on 2024-04-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
