# Generated by Django 5.0.3 on 2024-04-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesmodel',
            name='article_image',
            field=models.ImageField(upload_to='article_photos/'),
        ),
    ]
