# Generated by Django 5.0.3 on 2024-04-01 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampersCaravans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_registration', models.PositiveIntegerField()),
                ('type_of_engine', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('LPG', 'LPG')], max_length=10)),
                ('type_of_gear', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('seats', models.PositiveSmallIntegerField()),
                ('vehicle_image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('vehicle_type', models.CharField(choices=[('caravan', 'Caravan'), ('camper', 'Camper')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rentalluser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_registration', models.PositiveIntegerField()),
                ('type_of_engine', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('LPG', 'LPG')], max_length=10)),
                ('type_of_gear', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('seats', models.PositiveSmallIntegerField()),
                ('vehicle_image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('car_type', models.CharField(choices=[('sedan', 'Sedan'), ('SUV', 'SUV'), ('coupe', 'Coupe'), ('cabriolet', 'Cabriolet'), ('estate car', 'Estate Car')], max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rentalluser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2)])),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_registration', models.PositiveIntegerField()),
                ('type_of_engine', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('LPG', 'LPG')], max_length=10)),
                ('type_of_gear', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=10)),
                ('seats', models.PositiveSmallIntegerField()),
                ('vehicle_image', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('payload_weight', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rentalluser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
