# Generated by Django 5.0.3 on 2024-04-08 06:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camperscaravans',
            name='city',
            field=models.CharField(default=datetime.datetime(2024, 4, 8, 6, 21, 11, 101767, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camperscaravans',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 8, 6, 21, 40, 310451, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default=datetime.datetime(2024, 4, 8, 6, 21, 49, 711996, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 8, 6, 22, 3, 814613, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='published',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 4, 8, 6, 22, 31, 647801, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camperscaravans',
            name='vehicle_image',
            field=models.ImageField(upload_to='vehicle_images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_image',
            field=models.ImageField(upload_to='vehicle_images'),
        ),
        migrations.AlterField(
            model_name='van',
            name='vehicle_image',
            field=models.ImageField(upload_to='vehicle_images'),
        ),
    ]
