# Generated by Django 5.0.3 on 2024-04-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_offers', '0004_rename_vehicle_type_camperscaravans_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camperscaravans',
            name='type',
            field=models.CharField(choices=[('CARAVAN', 'CARAVAN'), ('CAMPER', 'CAMPER')], max_length=10),
        ),
    ]
